### ISSUE TITLE
FreeBSD x64 support

### ISSUE THREAD

**Issue by mnpenner** [imagemin/optipng-bin#64]
```
$ npm i optipng-bin
-
> optipng-bin@3.0.4 postinstall /usr/local/myproject/node_modules/optipng-bin
> node lib/install.js

ELF interpreter /libexec/ld-elf.so.1 not found
  ⚠ The `/usr/local/myproject/node_modules/optipng-bin/vendor/optipng` binary doesn't seem to work correctly
  ⚠ optipng pre-build test failed
  ℹ compiling from source
  ✖ Error: ./configure --with-system-zlib --prefix="/usr/local/myproject/node_modules/optipng-bin/vendor" --bindir="/usr/local/myproject/node_modules/optipng-bin/vendor" && make install
Command failed: /bin/sh -c make install
usage: cp [-R [-H | -L | -P]] [-f | -i | -n] [-alpvx] source_file target_file
       cp [-R [-H | -L | -P]] [-f | -i | -n] [-alpvx] source_file ... target_directory

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
optipng-bin@3.0.4 node_modules/optipng-bin
├── logalot@2.1.0 (figures@1.4.0, squeak@1.3.0)
├── bin-wrapper@3.0.2 (os-filter-obj@1.0.3, lazy-req@1.1.0, each-async@1.1.1, bin-check@2.0.0, bin-version-check@2.1.0, download@4.4.3)
└── bin-build@2.2.0 (rimraf@2.5.0, exec-series@1.0.2, url-regex@3.1.0, archive-type@3.2.0, tempfile@1.1.1, decompress@3.0.0, download@4.4.3)
```

I'm guessing [this guy](https://github.com/imagemin/optipng-bin/blob/master/vendor/freebsd/optipng) is 32-bit?

I'll try to build you a 64-bit one if you're willing to accept a PR.

**Comment by mnpenner** [comment]
I couldn't get [OptiPNG](http://optipng.sourceforge.net/) to build.

```
/tmp/optipng-0.7.5$ make
cd src/optipng &&  make &&  cd ../..
cd ../libpng &&  make -f Makefile PNGLIBCONF_H_PREBUILT=pnglibconf.h.optipng &&  cd ../optipng
cp  pnglibconf.h
usage: cp [-R [-H | -L | -P]] [-f | -i | -n] [-alpvx] source_file target_file
       cp [-R [-H | -L | -P]] [-f | -i | -n] [-alpvx] source_file ... target_directory
*** Error code 64

Stop.
make[2]: stopped in /tmp/optipng-0.7.5/src/libpng
*** Error code 1

Stop.
make[1]: stopped in /tmp/optipng-0.7.5/src/optipng
*** Error code 1

Stop.
make: stopped in /tmp/optipng-0.7.5
```

and

```
/tmp/optipng-mercurial$ make
cd src/optipng &&  make &&  cd ../..
cc -c  -O -I../opnglib/include  -I../opngreduc  -I../pngxtern  -I../zlib  -I../libpng  -I../sysexits -o optipng.o optipng.c
cc -c  -O -I../opnglib/include  -I../opngreduc  -I../pngxtern  -I../zlib  -I../libpng  -I../sysexits -o strconv.o strconv.c
cd ../opnglib &&  make -f Makefile libopng.a &&  cd ../optipng
cc -c  -O -I../opngreduc  -I../pngxtern  -I../libpng  -I../zlib  -I../gifread  -I../pnmio  -I../minitiff  -I../cexcept  -I../sysexits -Iinclude -o src/opngcore/codec.o src/opngcore/codec.c
src/opngcore/codec.c:372:17: warning: 'png_data_freer' is deprecated [-Wdeprecated-declarations]
                png_data_freer(context->libpng_ptr, context->info_ptr,
                ^
../libpng/png.h:1956:23: note: 'png_data_freer' declared here
PNG_EXPORTA(99, void, png_data_freer, (png_const_structrp png_ptr,
                      ^
../libpng/pngconf.h:327:50: note: expanded from macro 'PNG_EXPORTA'
      PNG_FUNCTION(PNG_EXPORT_TYPE(type),(PNGAPI name),PNGARG(args), \
                                                 ^
../libpng/pngconf.h:313:70: note: expanded from macro 'PNG_FUNCTION'
#  define PNG_FUNCTION(type, name, args, attributes) attributes type name args
                                                                     ^
src/opngcore/codec.c:722:5: warning: 'png_data_freer' is deprecated [-Wdeprecated-declarations]
    png_data_freer(context->libpng_ptr, context->info_ptr,
    ^
../libpng/png.h:1956:23: note: 'png_data_freer' declared here
PNG_EXPORTA(99, void, png_data_freer, (png_const_structrp png_ptr,
                      ^
../libpng/pngconf.h:327:50: note: expanded from macro 'PNG_EXPORTA'
      PNG_FUNCTION(PNG_EXPORT_TYPE(type),(PNGAPI name),PNGARG(args), \
                                                 ^
../libpng/pngconf.h:313:70: note: expanded from macro 'PNG_FUNCTION'
#  define PNG_FUNCTION(type, name, args, attributes) attributes type name args
                                                                     ^
src/opngcore/codec.c:822:5: warning: 'png_data_freer' is deprecated [-Wdeprecated-declarations]
    png_data_freer(context->libpng_ptr, context->info_ptr,
    ^
../libpng/png.h:1956:23: note: 'png_data_freer' declared here
PNG_EXPORTA(99, void, png_data_freer, (png_const_structrp png_ptr,
                      ^
../libpng/pngconf.h:327:50: note: expanded from macro 'PNG_EXPORTA'
      PNG_FUNCTION(PNG_EXPORT_TYPE(type),(PNGAPI name),PNGARG(args), \
                                                 ^
../libpng/pngconf.h:313:70: note: expanded from macro 'PNG_FUNCTION'
#  define PNG_FUNCTION(type, name, args, attributes) attributes type name args
                                                                     ^
3 warnings generated.
cc -c  -O -I../opngreduc  -I../pngxtern  -I../libpng  -I../zlib  -I../gifread  -I../pnmio  -I../minitiff  -I../cexcept  -I../sysexits -Iinclude -o src/opngcore/image.o src/opngcore/image.c
cc -c  -O -I../opngreduc  -I../pngxtern  -I../libpng  -I../zlib  -I../gifread  -I../pnmio  -I../minitiff  -I../cexcept  -I../sysexits -Iinclude -o src/opngcore/ioenv.o src/opngcore/ioenv.c
cc -c  -O -I../opngreduc  -I../pngxtern  -I../libpng  -I../zlib  -I../gifread  -I../pnmio  -I../minitiff  -I../cexcept  -I../sysexits -Iinclude -o src/opngcore/logger.o src/opngcore/logger.c
cc -c  -O -I../opngreduc  -I../pngxtern  -I../libpng  -I../zlib  -I../gifread  -I../pnmio  -I../minitiff  -I../cexcept  -I../sysexits -Iinclude -o src/opngcore/optim.o src/opngcore/optim.c
cc -c  -O -I../opngreduc  -I../pngxtern  -I../libpng  -I../zlib  -I../gifread  -I../pnmio  -I../minitiff  -I../cexcept  -I../sysexits -Iinclude -o src/opngcore/util.o src/opngcore/util.c
cc -c  -O -I../opngreduc  -I../pngxtern  -I../libpng  -I../zlib  -I../gifread  -I../pnmio  -I../minitiff  -I../cexcept  -I../sysexits -Iinclude -o src/opngcore/version.o src/opngcore/version.c
cc -c  -O -I../opngreduc  -I../pngxtern  -I../libpng  -I../zlib  -I../gifread  -I../pnmio  -I../minitiff  -I../cexcept  -I../sysexits -Iinclude -o src/opngtrans/apply.o src/opngtrans/apply.c
cc -c  -O -I../opngreduc  -I../pngxtern  -I../libpng  -I../zlib  -I../gifread  -I../pnmio  -I../minitiff  -I../cexcept  -I../sysexits -Iinclude -o src/opngtrans/chunksig.o src/opngtrans/chunksig.c
cc -c  -O -I../opngreduc  -I../pngxtern  -I../libpng  -I../zlib  -I../gifread  -I../pnmio  -I../minitiff  -I../cexcept  -I../sysexits -Iinclude -o src/opngtrans/parser.o src/opngtrans/parser.c
cc -c  -O -I../opngreduc  -I../pngxtern  -I../libpng  -I../zlib  -I../gifread  -I../pnmio  -I../minitiff  -I../cexcept  -I../sysexits -Iinclude -o src/opngtrans/trans.o src/opngtrans/trans.c
cc -c  -O -Iinclude -o src/optk/bits.o src/optk/bits.c
cc -c  -O -Iinclude -o src/optk/io.o src/optk/io.c
src/optk/io.c:770:13: warning: implicit declaration of function 'utimensat' is invalid in C99 [-Wimplicit-function-declaration]
        if (utimensat(AT_FDCWD, dest_path, times, 0) != 0)
            ^
1 warning generated.
cc -c  -O -o src/optk/wildargs.o src/optk/wildargs.c
ar cru libopng.a src/opngcore/codec.o  src/opngcore/image.o  src/opngcore/ioenv.o  src/opngcore/logger.o  src/opngcore/optim.o  src/opngcore/util.o  src/opngcore/version.o src/opngtrans/apply.o  src/opngtrans/chunksig.o  src/opngtrans/parser.o  src/opngtrans/trans.o src/optk/bits.o  src/optk/io.o  src/optk/wildargs.o
ranlib libopng.a
cd ../opngreduc &&  make -f Makefile libopngreduc.a &&  cd ../optipng
cc -c  -O -I../zlib  -I../libpng -o opngreduc.o opngreduc.c
ar cru libopngreduc.a opngreduc.o
ranlib libopngreduc.a
cd ../zlib &&  make -f Makefile libz.a &&  cd ../optipng
cc -O -c adler32.c
cc -O -c crc32.c
cc -O -c deflate.c
cc -O -c infback.c
cc -O -c inffast.c
cc -O -c inflate.c
cc -O -c inftrees.c
cc -O -c trees.c
cc -O -c zutil.c
cc -O -c compress.c
cc -O -c uncompr.c
cc -O -c gzclose.c
cc -O -c gzlib.c
cc -O -c gzread.c
cc -O -c gzwrite.c
ar rc libz.a adler32.o crc32.o deflate.o infback.o inffast.o inflate.o inftrees.o trees.o zutil.o compress.o uncompr.o gzclose.o gzlib.o gzread.o gzwrite.o 
cd ../libpng &&  make -f scripts/makefile.std libpng.a &&  cd ../optipng
rm -f pnglibconf.dfn pnglibconf.pre pnglibconf.tmp
echo "Calling awk from scripts/pnglibconf.mak" >&2
Calling awk from scripts/pnglibconf.mak
echo "If 'awk' crashes try a better awk (e.g. AWK='nawk')" >&2
If 'awk' crashes try a better awk (e.g. AWK='nawk')
awk -f scripts/options.awk out="pnglibconf.pre" version=search pngconf.h scripts/pnglibconf.dfa pngusr.dfa  1>&2
awk -f scripts/options.awk out="pnglibconf.tmp" pnglibconf.pre 1>&2
mv pnglibconf.tmp pnglibconf.dfn
rm -f pnglibconf.h pnglibconf.c pnglibconf.out pnglibconf.tmp
echo '#include "pnglibconf.dfn"' >pnglibconf.c
echo "If 'cc -E' crashes try /lib/cpp (e.g. CPP='/lib/cpp')" >&2
If 'cc -E' crashes try /lib/cpp (e.g. CPP='/lib/cpp')
cc -E  pnglibconf.c >pnglibconf.out
awk -f "scripts/dfn.awk" out="pnglibconf.tmp" pnglibconf.out 1>&2
mv pnglibconf.tmp pnglibconf.h
cc -I../zlib -O -c png.c
In file included from png.c:14:
./pngpriv.h:816:4: error: ZLIB_VERNUM != PNG_ZLIB_VERNUM "-I (include path) error: see the notes in pngpriv.h"
#  error ZLIB_VERNUM != PNG_ZLIB_VERNUM \
   ^
1 error generated.
*** Error code 1

Stop.
make[2]: stopped in /tmp/optipng-mercurial/src/libpng
*** Error code 1

Stop.
make[1]: stopped in /tmp/optipng-mercurial/src/optipng
*** Error code 1

Stop.
make: stopped in /tmp/optipng-mercurial
```

However, there is a [port](http://portsmon.freebsd.org/portoverview.py?category=graphics&portname=optipng) that works fine. I'll commit that shortly.
