### ISSUE TITLE
Cannot execute optipng binary file after updating Node.js to 5.9.1

### ISSUE THREAD

**Issue by 2oo** [imagemin/optipng-bin#67]
Worked fine on 5.9.0. I'm on OS X El Capitan 10.11.3.

Now I get this error:

```
ERROR in ./src/core/components/Navbar/UserControls/assets/profile.png
Module build failed: Error: Command failed: /project/node_modules/optipng-bin/vendor/optipng -strip all -clobber -force -fix -out /var/folders/3x/8912scxx07xdrrvpyljfcl140000gt/T/401ff2af-988e-49eb-9423-c89a2ba6f46d /var/folders/3x/8912scxx07xdrrvpyljfcl140000gt/T/4cabb390-60ff-4501-8078-fe3a39d3dad3
/project/node_modules/optipng-bin/vendor/optipng: /project/node_modules/optipng-bin/vendor/optipng: cannot execute binary file

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
 @ ./src/core/components/Navbar/UserControls/UserControls.js 71:68-99
```

It is ran through webpack with image-webpack-loader, but the same error occurs when executing file without any args.

**Comment by 2oo** [comment]
Sorry, my bad.
It was compiled inside virtual machine running Debian into mounted directory and I tried to run it from host. It's working fine.
