### ISSUE TITLE
Broken on Node 6.5.0

### ISSUE THREAD

**Issue by filingroove** [imagemin/optipng-bin#79]
Throws the following on install. Was working perfectly on node 6.0.0

```
> optipng-bin@0.3.11 postinstall /Users/yuriysichkovskiy/dev/wavescore-site/node_modules/optipng-bin
> node index.js

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received { url: 'https://raw.github.com/imagemin/optipng-bin/v0.3.11/vendor/osx/optipng',
  name: 'optipng',
  os: 'darwin' }
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1357:5)
    at /Users/.../node_modules/download/index.js:35:43
    at each (/Users/.../node_modules/each-async/each-async.js:63:4)
    at module.exports (/Users/.../node_modules/download/index.js:33:5)
    at /Users/.../node_modules/bin-wrapper/index.js:108:20
    at /Users/.../node_modules/bin-wrapper/index.js:141:24
    at /Users/.../node_modules/bin-check/index.js:30:20
    at /Users/.../node_modules/executable/index.js:39:20
    at FSReqWrap.oncomplete (fs.js:123:15)
npm WARN install:optipng-bin@0.3.11 optipng-bin@0.3.11 postinstall: `node index.js`
npm WARN install:optipng-bin@0.3.11 Exit status 1
```

**Comment by shinnn** [comment]
> optipng-bin@0.3.11

You're using ancient version. Upgrade to the latest optipng-bin.
