### ISSUE TITLE
DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

### ISSUE THREAD

**Issue by HannieLee** [imagemin/optipng-bin#80]
Node v7.3.0   MacOS v10.11.3

(node:75729) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Unhandled rejection Error: spawn /Users/Hannie/Workspace/ChelaileH5/node_modules/.3.1.2@optipng-bin/vendor/optipng ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by shinnn** [comment]
Can you show us the output of:

```
npm ls optipng-bin
```

**Comment by HannieLee** [comment]
che-gulp@1.0.0 /Users/Hannie/Workspace/ChelaileH5
├─┬ gulp-imagemin@2.4.0 -> /Users/Hannie/Workspace/ChelaileH5/node_modules/.2.4.0@gulp-imagemin
│ └─┬ imagemin@4.0.0
│   └─┬ imagemin-optipng@4.3.0
│     └── optipng-bin@3.1.2
└── optipng-bin@3.1.2  -> /Users/Hannie/Workspace/ChelaileH5/node_modules/.3.1.2@optipng-bin

**Comment by shinnn** [comment]
This module doesn't use `os.tmpDir()` at runtime. Probably the first line and the rest indicate different errors, and the former was emitted by another module.

```
(node:75729) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
```

---------

```
Unhandled rejection Error: spawn /Users/Hannie/Workspace/ChelaileH5/node_modules/.3.1.2@optipng-bin/vendor/optipng ENOENT
at exports._errnoException (util.js:1022:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
at onErrorNT (internal/child_process.js:359:16)
at _combinedTickCallback (internal/process/next_tick.js:74:11)
at process._tickCallback (internal/process/next_tick.js:98:9)
```
