### ISSUE TITLE
alpine-node:4 npm install > Error: Cannot find module './lib/symlink'

### ISSUE THREAD

**Issue by airtonix** [imagemin/optipng-bin#82]
```
optipng-bin@3.1.2 postinstall /tmp/git-resource-destination.JfGPDb/node_modules/optipng-bin
> node lib/install.js

module.js:327
    throw err;
    ^

Error: Cannot find module './lib/symlink'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/tmp/git-resource-destination.JfGPDb/node_modules/vinyl-fs/index.js:6:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

**Comment by shinnn** [comment]
http://www.catb.org/~esr/faqs/smart-questions.html#forum Go to 

> `/tmp/git-resource-destination.JfGPDb/node_modules/vinyl-fs/index.js:6:12`

Go to https://github.com/gulpjs/vinyl-fs/issues.
