### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by mccstan** [imagemin/optipng-bin#88]
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received { url: 'https://raw.github.com/imagemin/optipng-bin/v0.3.11/vendor/linux/x64/optipng',
  name: 'optipng',
  os: 'linux',
  arch: 'x64' }
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at /home/mccstan/Projects/mean-chat/node_modules/download/index.js:35:43
    at each (/home/mccstan/Projects/mean-chat/node_modules/each-async/each-async.js:63:4)
    at module.exports (/home/mccstan/Projects/mean-chat/node_modules/download/index.js:33:5)
    at /home/mccstan/Projects/mean-chat/node_modules/bin-wrapper/index.js:108:20
    at /home/mccstan/Projects/mean-chat/node_modules/bin-wrapper/index.js:141:24
    at /home/mccstan/Projects/mean-chat/node_modules/bin-check/index.js:30:20
    at /home/mccstan/Projects/mean-chat/node_modules/executable/index.js:39:20
    at FSReqWrap.oncomplete (fs.js:114:15)

npm ERR! Linux 3.10.0-514.10.2.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "rebuild"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! optipng-bin@0.3.11 postinstall: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the optipng-bin@0.3.11 postinstall script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the optipng-bin package,
npm ERR! not with npm itself.

**Comment by bradbaris** [comment]
Update `optipng-bin` from `0.3.11` to `3.1.4`.

**Comment by danvitoriano** [comment]
Hey guys...
All Travis buildings are broken, in all node versions.
And I always get `Error: spawn /var/lib/jenkins/workspace/.../node_modules/optipng-bin/vendor/optipng ENOENT`
How can I fix this problem? I've already tried all open/closed issues, but from time to time the error reappear.
Thank you!

**Comment by callmez** [comment]
same

**Comment by pgnd** [comment]
similar to the issue here, and @

```
	https://github.com/npm/npm/issues/8682
```

a clean install from current sources, as root, fails

```
yarn add --dev imagemin-optipng@^5.2
yarn add v0.24.6
	[1/4] Resolving packages...
	[2/4] Fetching packages...
	[3/4] Linking dependencies...
	[4/4] Building fresh packages...
	[1/1] ⠈ optipng-bin:   ℹ compiling from source
	[-/1] ⠈ waiting...
	[-/1] ⠈ waiting...
	[-/1] ⠈ waiting...
	error /srv/www/test/node_modules/optipng-bin: Command failed.
	Exit code: 1
	Command: sh
	Arguments: -c node lib/install.js
	Directory: /srv/www/test/node_modules/optipng-bin
	Output:
	⚠ Couldn't execute the `/srv/www/test/node_modules/optipng-bin/vendor/optipng` binary. Make sure it has the right permissions.
	  ⚠ optipng pre-build test failed
	  ℹ compiling from source
	path.js:28
	    throw new TypeError('Path must be a string. Received ' + inspect(path));
	    ^

	TypeError: Path must be a string. Received undefined
	    at assertPath (path.js:28:11)
	    at Object.resolve (path.js:1167:7)
	    at mkdirp (/srv/www/test/node_modules/fs-mkdirp-stream/mkdirp.js:17:18)
	    at onDirpath (/srv/www/test/node_modules/fs-mkdirp-stream/index.js:31:9)
	    at dirpath (/srv/www/test/node_modules/vinyl-fs/lib/dest/index.js:26:5)
	    at DestroyableTransform.makeFileDirs [as _transform] (/srv/www/test/node_modules/fs-mkdirp-stream/index.js:24:7)
	    at DestroyableTransform.Transform._read (/srv/www/test/node_modules/readable-stream/lib/_stream_transform.js:182:10)
	    at DestroyableTransform.Transform._write (/srv/www/test/node_modules/readable-stream/lib/_stream_transform.js:170:83)
	    at doWrite (/srv/www/test/node_modules/readable-stream/lib/_stream_writable.js:405:64)
	    at writeOrBuffer (/srv/www/test/node_modules/readable-stream/lib/_stream_writable.js:394:5)
	info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by danvitoriano** [comment]
No @hbakhtiyor I did not resolved. 
I removed the module from my gulp tasks 😢

**Comment by 1000ch** [comment]
This seems to be outdated. Please raise this issue if you face it again.
