### ISSUE TITLE
Fix install.js error message

### ISSUE THREAD

**Issue by NikitaEgorov** [imagemin/optipng-bin#92]
Please change
```
if (err) {
	log.error(err.stack);
	return;
}
```

to 

```
if (err) {
	log.error(err);
	return;
}
```

**Comment by sindresorhus** [comment]
Why? `.stack` includes the error message too:

```
(new Error('foo')).stack
"Error: foo
    at <anonymous>:1:2"
```

**Comment by NikitaEgorov** [comment]
In build process it is look like:
```
/build/node_modules/optipng-bin # node lib/install.js
  ⚠ spawn /build/node_modules/optipng-bin/vendor/optipng ENOENT
  ⚠ optipng pre-build test failed
  ℹ compiling from source
  ✖ Error: ./configure --with-system-zlib --prefix="/build/node_modules/optipng-bin/vendor" --bindir="/build/node_modules/optipng-bin/vendor" && make install
Command failed: ./configure --with-system-zlib --prefix="/build/node_modules/optipng-bin/vendor" --bindir="/build/node_modules/optipng-bin/vendor"

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```
